apiVersion: v1
kind: Service
metadata:
    name: "locdevnew-d5ee"
    labels:
        app: "locdevnew-d5ee"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "locdevnew-d5ee"